### PR TITLE
Added DAppBrowser and Navbar

### LINKED ISSUE #15: Integrating a DApp browser inside the website
image

I have made it but haven't styled it yet

### PR DESCRIPTION
**Pull request by ayush-848**
Closes #15 
image

### CODE REVIEW

**Comment by ayush-848** [comment]
@VedantAnand17 please check
I created a home component to and had to rearrange the props

**Comment by VedantAnand17** [comment]
Good work man 👏 
What I meant to say by NavBar was kindly edit the option on top to navigate between home page and dApp browser, kindly rectify it and also check the responsiveness :)

**Comment by ayush-848** [comment]
> Good work man 👏 What I meant to say by NavBar was kindly edit the option on top to navigate between home page and dApp browser, kindly rectify it and also check the responsiveness :)

Should i remove the home about options from navbar

**Comment by ayush-848** [comment]
image
@VedantAnand17 see this

**Comment by ayush-848** [comment]
> Kindly comment out the service and contact pages :)

image
done

**Comment by VedantAnand17** [comment]
NavBar is unresponsive and has no home button 😅

**Comment by ayush-848** [comment]
> NavBar is unresponsive and has no home button 😅

@VedantAnand17 Oh i forgot about the responsive ness
and the logo is the home button itself

**Comment by ayush-848** [comment]
Now check

**Comment by ayush-848** [comment]
@VedantAnand17 please merge it if it is ok

**Comment by VedantAnand17** [comment]
Testing

**Comment by ayush-848** [comment]
@VedantAnand17 add the labels in the PRs too

**Pull request merged**
